### ISSUE TITLE
404 when opening a dashboard

### ISSUE THREAD

**Issue by xlson** [ripienaar/gdash#21] opened 2012-02-01 14:26 UTC
I'm not that familiar with the Ruby world but I've been able to start gdash using rackup and shotgun. I've copied the sample graphite config to my templates folder and can see it listed on the gdash frontpage. When I click on a dashboard I get a 404 and Sinatra claims there is no such route.

Shotgun shows these exceptions in the log:
```Exception`LoadError' at /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36 - no such file to load -- sinatra
Exception `NoMethodError' at /usr/lib/ruby/1.8/rational.rb:78 - undefined method`gcd' for Rational(1, 2):Rational
Exception `Sinatra::NotFound' at /usr/lib/ruby/gems/1.8/gems/sinatra-1.3.2/lib/sinatra/base.rb:837 - Sinatra::NotFound
Exception`WEBrick::HTTPStatus::EOFError' at /usr/lib/ruby/1.8/webrick/httpserver.rb:55 - WEBrick::HTTPStatus::EOFError

```
I'd really appreciate any help with getting gdash running. My OS is Ubuntu and I'm using Ruby 1.8.7.
```

**Comment by ghost** [comment] 2012-02-01 14:30
The problem seems to be that you didnt install sinatra:

   Exception `LoadError' at /usr/local/lib/site_ruby/1.8/rubygems/custom_require.rb:36 - no such file to load -- sinatra

**Comment by xlson** [comment] 2012-02-01 14:39
The strange part is that I've run gem install sinatra and that I get an
error message that I expect can only come from sinatra (in the browser):
"Sinatra doesn't know this ditty.".

On Wed, Feb 1, 2012 at 3:30 PM, pinetec <
reply@reply.github.com

**Comment by ripienaar** [comment] 2012-02-01 14:42
whats the url it tires to access and fail?

**Comment by xlson** [comment] 2012-02-01 14:44
The url is http://10.211.55.6:9393/foo/
my template dir is: /home/leo/gdash-templates and contains the foo-folder with the sample files (dash.yaml and so on).

**Comment by ripienaar** [comment] 2012-02-01 14:49
And thats a url it generates for you when you visit the index page or on your made up? cos that is indeed not a valid url.

Valid url would be something like /foo/graphname/ where graphname is one of the .graph files you put in the foo directory

**Comment by xlson** [comment] 2012-02-01 14:54
The url is generated by the index page.

That got me a bit further, now I get an error from the webapp instead: "No dashboard called network found in network/..".

**Comment by xlson** [comment] 2012-02-01 15:28
I guess I must be doing something wrong as both the index page is generating the wrong urls and the right ones does not work. Can't figure out what tho, can't find anything that seem like it could be wrong in my configuration.

**Comment by damm** [comment] 2012-02-14 03:13
I was able to reproduce this easily; resolving it seems to be a bit dubious.

**Comment by ripienaar** [comment] 2012-02-14 08:43
maybe you can provide steps then to reproduce? I set up a new instance this weekend and it just worked but maybe I am doing something out of habit thats not obvious

**Comment by damm** [comment] 2012-02-14 18:33
I likely took the wrong steps; but what I did was this.
- Fork gdash
  - Clone the fork
  - copy samples to a directory called graphs with the name of acheron (yes gdash does pickup the name)
  - yes I did modify the samples to real graph names; they were not just copied as is.  
  - modify gdash.yml to point to the right graphite install and the right whisper directory.

bundle exec rackup

Try and view your graphs.  I know there's other users out there that do work; so it must be something i'm doing odd.

**Comment by ripienaar** [comment] 2012-02-14 19:49
Did you do something like "bundle install --path vendor/bundle" to install all the gems it needs into your project?

**Comment by damm** [comment] 2012-02-14 19:55
% mkdir -p vendor/cache            l                                                      ~/gdash (master ⚡) desolation
% bundle --path /tmp/shitty install                                                      ~/gdash (master ⚡) desolation
Fetching gem metadata from http://rubygems.org/.......
Using daemons (1.1.8) 
Installing eventmachine (0.12.10) with native extensions 
Installing kgio (2.7.0) with native extensions 
Installing rack (1.3.4) 
Installing rack-protection (1.1.4) 
Installing raindrops (0.8.0) with native extensions 
Installing shotgun (0.9) 
Installing tilt (1.3.3) 
Installing sinatra (1.3.1) 
Installing thin (1.3.1) with native extensions 
Installing unicorn (4.1.1) with native extensions 
Using bundler (1.1.rc.7) 
Updating .gem files in vendor/cache
- daemons-1.1.8.gem
- eventmachine-0.12.10.gem
- kgio-2.7.0.gem
- rack-1.3.4.gem
- rack-protection-1.1.4.gem
- raindrops-0.8.0.gem
- shotgun-0.9.gem
- tilt-1.3.3.gem
- sinatra-1.3.1.gem
- thin-1.3.1.gem
- unicorn-4.1.1.gem
  Your bundle is complete! It was installed into /tmp/shitty
  % bundle exec rackup                                                                     ~/gdash (master ⚡) desolation
  [2012-02-14 19:54:12] INFO  WEBrick 1.3.1
  [2012-02-14 19:54:12] INFO  ruby 1.9.3 (2011-10-30) [x86_64-linux]
  [2012-02-14 19:54:12] INFO  WEBrick::HTTPServer#start: pid=29204 port=9292
  10.1.10.18 - - [14/Feb/2012 19:54:17] "GET / HTTP/1.1" 200 2272 0.0211
  10.1.10.18 - - [14/Feb/2012 19:54:19] "GET /acheron/ HTTP/1.1" 404 445 0.0010

**Comment by ripienaar** [comment] 2012-02-14 20:02
And indeed, there is no page like that. It's not a valid URL, hence 404.

You visit / which will give you an overview of all your dashboard, this would create urls like:

```
http://your.gdah/dashboards/kvm1
```

given a directory structure like:

```
graph_templates
`-- dashboards
    |-- README.md
     `-- kvm1
        |-- dash.yaml
         `-- ssd_write.graph
```

**Comment by damm** [comment] 2012-02-14 20:04
That was the ticket.  I had the directory layout wrong, updated and fixed!  Thanks!

**Closed as completed** 2012-02-14 20:05 UTC
